spring:
  application:
    name: toeic-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret-key: ${JWT_SECRET_KEY}
server:
  port: 8888

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /v3/api-docs
